export default [
    { name: 'Chaos' },
    { name: 'Command' },
    { name: 'Death' },
    { name: 'Dissonance' },
    { name: 'Enigma' },
    { name: 'Evolution' },
    { name: 'Frailty' },
    { name: 'Glass' },
    { name: 'Honor' },
    { name: 'Kin' },
    { name: 'Metamorphosis' },
    { name: 'Sacrifice' },
    { name: 'Soul' },
    { name: 'Spite' },
    { name: 'Swarms' },
    { name: 'Vengeance' },
];
