export default [
    { name: 'Abandoned Aqueduct' },
    { name: 'Abyssal Depths' },
    { name: 'Commencement' },
    { name: 'Distant Roost' },
    { name: 'Rallypoint Delta' },
    { name: 'Scorched Acres' },
    { name: "Siren's Call" },
    { name: 'Sky Meadow' },
    { name: 'Sundered Grove' },
    { name: 'Titanic Plains' },
    { name: 'Wetland Aspect' },
    { name: 'A Moment, Fractured' },
    { name: 'A Moment, Whole' },
    { name: 'Bazaar Between Time' },
    { name: "Bulwark's Ambry" },
    { name: 'Gilded Coast' },
    { name: 'Void Fields' },
];
