export default [
    { name: 'Teleporter' },
    { name: 'Newt Altars' },
    { name: 'Escape Pod' },
    { name: 'Radio Scanner' },
    { name: 'Launch Pads' },
    { name: 'Chests' },
    { name: 'Lunar Pod' },
    { name: 'Barrel' },
    { name: '3D Printers' },
    { name: 'Scrapper' },
    { name: 'Cleansing Pool' },
    { name: 'Altar of Gold' },
    { name: 'Shrine of Blood' },
    { name: 'Shrine of Chance' },
    { name: 'Shrine of Combat' },
    { name: 'Shrine of Order' },
    { name: 'Shrine of the Mountain' },
    { name: 'Shrine of the Woods' },
];
