export default [
    { name: 'A Moment, Fractured' },
    { name: 'Abandoned Aqueduct' },
    { name: 'Abyssal Depths' },
    { name: "Bulwark's Ambry" },
    { name: 'Commencement' },
    { name: 'Sky Meadow' },
    { name: 'Titanic Plains' },
    { name: 'Wetland Aspect' },
    { name: 'Aegis' },
    { name: 'Alien Head' },
    { name: 'Ancestral Incubator' },
    { name: 'Bandolier' },
    { name: 'Brainstalks' },
    { name: 'Brittle Crown' },
    { name: 'Bundle of Fireworks' },
    { name: 'Ceremonial Dagger' },
    { name: 'Chronobauble' },
    { name: 'Death Mark' },
    { name: 'Energy Drink' },
    { name: 'Focused Convergence' },
    { name: 'Fuel Cell' },
    { name: 'Gasoline' },
    { name: "Ghor's Tome" },
    { name: 'H3AD-5T v2' },
    { name: 'Halcyon Seed' },
    { name: 'Hardlight Afterburner' },
    { name: 'Interstellar Desk Plant' },
    { name: "Kjaro's Band" },
    { name: 'Lepton Daisy' },
    { name: 'Little Disciple' },
    { name: 'Medkit' },
    { name: 'Mired Urn' },
    { name: 'Molten Perforator' },
    { name: "N'kuhana's Opinion" },
    { name: 'Old Guillotine' },
    { name: 'Old War Stealthkit' },
    { name: 'Personal Shield Generator' },
    { name: 'Predatory Instincts' },
    { name: 'Purity' },
    { name: "Queen's Gland" },
    { name: 'Rejuvenation Rack' },
    { name: 'Repulsion Armor Plate' },
    { name: 'Rose Buckler' },
    { name: "Runald's Band" },
    { name: 'Rusted Key' },
    { name: 'Sentient Meat Hook' },
    { name: 'Shaped Glass' },
    { name: 'Shattering Justice' },
    { name: 'Shatterspleen' },
    { name: "Soldier's Syringe" },
    { name: 'Soulbound Catalyst' },
    { name: 'Squid Polyp' },
    { name: 'Sticky Bomb' },
    { name: 'Strides of Heresy' },
    { name: 'Topaz Brooch' },
    { name: 'Tougher Times' },
    { name: 'Transcendence' },
    { name: 'Unstable Tesla Coil' },
    { name: 'Visions of Heresy' },
    { name: 'War Horn' },
    { name: 'Wax Quail' },
    { name: "Will-o'-the-wisp" },
    { name: 'Blast Shower' },
    { name: 'Forgive Me Please' },
    { name: 'Glowing Meteorite' },
    { name: 'Gnarled Woodsprite' },
    { name: "Gorag's Opus" },
    { name: 'Helfire Tincture' },
    { name: 'Jade Elephant' },
    { name: 'Milky Chrysalis' },
    { name: 'Ocular HUD' },
    { name: 'Preon Accumulator' },
    { name: 'Recycler' },
    { name: 'Sawmerang' },
    { name: 'Super Massive Leech' },
    { name: 'The Back-Up' },
    { name: 'The Crowdfunder' },
    { name: 'Artificer' },
    { name: 'Captain' },
    { name: 'Huntress' },
    { name: 'MUL-T' },
    { name: 'REX' },
    { name: 'Alloy Vulture' },
    { name: 'Alloy Worship Unit' },
    { name: 'Beetle' },
    { name: 'Beetle Guard' },
    { name: 'Clay Dunestrider' },
    { name: 'Imp' },
    { name: 'Jellyfish' },
    { name: 'Lunar Chimera (Golem)' },
    { name: 'Lunar Chimera (Wisp)' },
    { name: 'Mini Mushrum' },
    { name: 'Mithrix' },
    { name: 'Parent' },
    { name: 'Solus control Unit' },
    { name: 'Void Reaver' }
];